exclude: "/migrations/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black

  - repo: https://github.com/MarketSquare/robotframework-tidy
    rev: "3.3.2"
    hooks:
      - id: robotidy

  - repo: https://github.com/myint/eradicate
    rev: v2.1.0
    hooks:
      - id: eradicate
        args: [ "--error" ] # Do not automatically remove commented-out code

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.6
    hooks:
      - id: vulture

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-tidy-imports]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.982
#    hooks:
#      - id: mypy

#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.15.2
#    hooks:
#      - id: pylint

#  - repo: https://github.com/PyCQA/pydocstyle
#    rev: 6.1.1
#    hooks:
#      - id: pydocstyle
