from django.urls import path
from onboarding.views import (
    index,
    OnboardingIntroductionView,
    OnboardingChooseReportInfoView,
    OnboardingChooseReportTypeView,
    OnboardingSetupScanOOIInfoView,
    OnboardingSetupScanOOIDetailView,
    OnboardingSetClearanceLevelView,
    OnboardingSetupScanSelectPluginsView,
    OnboardingSetupScanOOIAddView,
    OnboardingReportView,
    DnsReportView,
    OnboardingIntroductionRegistrationView,
    OnboardingOrganizationSetupView,
    OnboardingOrganizationUpdateView,
    OnboardingIndemnificationSetupView,
    OnboardingChooseUserTypeView,
    make_superuser_redteamer,
    skip_onboarding,
    OnboardingAccountSetupIntroView,
    OnboardingAccountSetupAdminView,
    OnboardingAccountSetupRedTeamerView,
    OnboardingAccountSetupClientView,
)


urlpatterns = [
    path("", index, name="onboarding_index"),
    path(
        "step/introduction/",
        OnboardingIntroductionView.as_view(),
        name="step_introduction",
    ),
    path(
        "step/choose-report-info/",
        OnboardingChooseReportInfoView.as_view(),
        name="step_choose_report_info",
    ),
    path(
        "step/choose-report-type/",
        OnboardingChooseReportTypeView.as_view(),
        name="step_choose_report_type",
    ),
    path(
        "step/setup-scan/ooi/info/",
        OnboardingSetupScanOOIInfoView.as_view(),
        name="step_setup_scan_ooi_info",
    ),
    path(
        "step/setup-scan/ooi/detail/",
        OnboardingSetupScanOOIDetailView.as_view(),
        name="step_setup_scan_ooi_detail",
    ),
    path(
        "step/set-clearance-level/",
        OnboardingSetClearanceLevelView.as_view(),
        name="step_set_clearance_level",
    ),
    path(
        "step/setup-scan/select-plugins/",
        OnboardingSetupScanSelectPluginsView.as_view(),
        name="step_setup_scan_select_plugins",
    ),
    path(
        "step/setup-scan/<ooi_type>/",
        OnboardingSetupScanOOIAddView.as_view(),
        name="step_setup_scan_ooi_add",
    ),
    path(
        "step/report/",
        OnboardingReportView.as_view(),
        name="step_report",
    ),
    path(
        "step/report/dns-report/",
        DnsReportView.as_view(),
        name="dns_report",
    ),
    path(
        "step/introduction/registration/",
        OnboardingIntroductionRegistrationView.as_view(),
        name="step_introduction_registration",
    ),
    path(
        "step/organization-setup/",
        OnboardingOrganizationSetupView.as_view(),
        name="step_organization_setup",
    ),
    path(
        "step/organization-setup/<pk>/update/",
        OnboardingOrganizationUpdateView.as_view(),
        name="step_organization_update",
    ),
    path(
        "<organization_code>/step/indemnification-setup/",
        OnboardingIndemnificationSetupView.as_view(),
        name="step_indemnification_setup",
    ),
    path(
        "step/choose-user-type/",
        OnboardingChooseUserTypeView.as_view(),
        name="step_choose_user_type",
    ),
    path(
        "step/choose-user-type/switch",
        make_superuser_redteamer,
        name="switch_kat_user",
    ),
    path(
        "step/skip-onboarding",
        skip_onboarding,
        name="skip_onboarding",
    ),
    path(
        "step/account-setup/introduction/",
        OnboardingAccountSetupIntroView.as_view(),
        name="step_account_setup_intro",
    ),
    path(
        "step/account-setup/admin/",
        OnboardingAccountSetupAdminView.as_view(),
        name="step_account_setup_admin",
    ),
    path(
        "step/account-setup/red-teamer/",
        OnboardingAccountSetupRedTeamerView.as_view(),
        name="step_account_setup_red_teamer",
    ),
    path(
        "step/account-setup/client/",
        OnboardingAccountSetupClientView.as_view(),
        name="step_account_setup_client",
    ),
]
