# Generated by Django 3.2.16 on 2022-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OOIInformation',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(null=True)),
                ('consult_api', models.BooleanField(default=False)),
            ],
        ),
    ]
