name: package rocky for debian

on:
  push:
    tags:
      - v*

jobs:
  build_deb:

    runs-on: ubuntu-20.04
    env:
      working_directory: /usr/share/kat-rocky
      pkg_name: kat-rocky

    steps:
      - name: Set env
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_TAG}\"/" {} \;

      # TODO: proper deb package versions
      - name: Create directories for .deb package
        run: mkdir -p kat-rocky_${{env.RELEASE_VERSION}}/{data/usr/share/kat-rocky/app,data/usr/bin,debian}

      - name: Move app files to .deb directory
        run: |
          PACKAGE_FILES=(rocky
          assets
          crisis_room
          data
          export_migrations
          fmea
          locale
          onboarding
          rocky
          roeltje
          templates
          tools
          .env-dist
          LICENSE
          manage.py
          OOI_database_seed.json
          package.json
          Readme.md
          requirements.txt
          yarn.lock)

          for file in "${PACKAGE_FILES[@]}"; do
            cp -r $file kat-rocky_${{env.RELEASE_VERSION}}/data/usr/share/kat-rocky/app/
          done

      - name: Run yarn build for rocky
        shell: bash -l -eo pipefail {0}
        run: |
          nvm install v16
          nvm use
          yarn
          yarn build
        working-directory: kat-rocky_${{env.RELEASE_VERSION}}/data/usr/share/kat-rocky/app

      - name: Copy static package files
        run: |
          cp -r ./packaging/deb/* kat-rocky_${{env.RELEASE_VERSION}}/
          sed -i "s/_VERSION_/${{env.RELEASE_VERSION}}/g" kat-rocky_${{env.RELEASE_VERSION}}/debian/control

      # TODO: generate proper changelog
      - name: generate changelog
        run: |
          cat > debian/changelog << EOF
          kat-rocky (${{env.RELEASE_VERSION}}) unstable; urgency=low
            * view changes: https://github.com/minvws/nl-kat-rocky/releases/tag/${{env.RELEASE_TAG}}

           -- OpenKAT <maintainer@openkat.nl>  $(LANG=C date -R)

          EOF
        working-directory: kat-rocky_${{env.RELEASE_VERSION}}/

      - name: generate copyright file
        run: |
          sed -i "s|__URL__|${{github.repositoryUrl}}|" kat-rocky_${{env.RELEASE_VERSION}}/debian/copyright
          cat LICENSE | sed 's/^/  /' >> kat-rocky_${{env.RELEASE_VERSION}}/debian/copyright

      - name: Install required packages for building
        run: sudo apt install gettext devscripts debhelper -y

      - name: Create .deb
        run: dpkg-buildpackage -us -uc -b
        working-directory: kat-rocky_${{env.RELEASE_VERSION}}/

      - name: Upload .deb to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kat-rocky_${{ env.RELEASE_VERSION }}.deb
          path: kat-rocky_${{ env.RELEASE_VERSION }}_all.deb
