name: Run the test suite

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: nl-kat-rocky

      - name: Checkout octopoes
        uses: actions/checkout@v3
        with:
          repository: minvws/nl-kat-octopoes
          path: nl-kat-octopoes

      - name: Build image
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f base.yml  -f .ci/docker-compose.yml build --build-arg USER_UID="$(id -u)" --build-arg USER_GID="$(id -g)" rocky_tests
        working-directory: nl-kat-rocky

      - name: Run tests
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f base.yml  -f .ci/docker-compose.yml run --rm rocky_tests
        working-directory: nl-kat-rocky
