name: Run the Robot Framework tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "develop"
      - "main"

  workflow_run:
    workflows: [Create container image]
    types:
      - completed

env:
  OCTOPOES_TAG: 'main'
  KEIKO_TAG: 'main'
  MULA_TAG: 'main'
  BYTES_TAG: 'main'
  BOEFJES_TAG: 'main'
  COMPOSE_INTERACTIVE_NO_CLI: 1
  COMPOSE_FILE: '.ci/docker-compose-robot-coordination.yml'

jobs:
  End-to-End:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: nl-kat-rocky

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: nl-kat-rocky

      - name: Inject slug/short variables for branch names
        uses: rlespinasse/github-slug-action@v4

      - name: Check if Octopoes has matching branch
        id: octopoes-check
        run: docker inspect ghcr.io/minvws/nl-kat-octopoes:${{ env.GITHUB_REF_NAME_SLUG }}
        continue-on-error: true

      - name: Set branch tag if Octopoes has matching tag
        if: steps.octopoes-check.outcome == 'success'
        run: echo "OCTOPOES_TAG=${{ env.GITHUB_REF_NAME_SLUG }}" >> $GITHUB_ENV

      - name: Check if Keiko has matching branch
        id: keiko-check
        run: docker inspect ghcr.io/minvws/nl-kat-keiko:${{ env.GITHUB_REF_NAME_SLUG }}
        continue-on-error: true

      - name: Set branch tag if Keiko has matching tag
        if: steps.keiko-check.outcome == 'success'
        run: echo "KEIKO_TAG=${{ env.GITHUB_REF_NAME_SLUG }}" >> $GITHUB_ENV

      - name: Check if Mula has matching branch
        id: mula-check
        run: docker inspect ghcr.io/minvws/nl-kat-mula:${{ env.GITHUB_REF_NAME_SLUG }}
        continue-on-error: true

      - name: Set branch tag if Mula has matching tag
        if: steps.mula-check.outcome == 'success'
        run: echo "MULA_TAG=${{ env.GITHUB_REF_NAME_SLUG }}" >> $GITHUB_ENV

      - name: Check if Bytes has matching branch
        id: bytes-check
        run: docker inspect ghcr.io/minvws/nl-kat-bytes:${{ env.GITHUB_REF_NAME_SLUG }}
        continue-on-error: true

      - name: Set branch tag if Bytes has matching tag
        if: steps.bytes-check.outcome == 'success'
        run: echo "BYTES_TAG=${{ env.GITHUB_REF_NAME_SLUG }}" >> $GITHUB_ENV

      - name: Check if Boefjes has matching branch
        id: boefjes-check
        run: docker inspect ghcr.io/minvws/nl-kat-boefjes:${{ env.GITHUB_REF_NAME_SLUG }}
        continue-on-error: true

      - name: Set branch tag if Boefjes has matching tag
        if: steps.boefjes-check.outcome == 'success'
        run: echo "BOEFJES_TAG=${{ env.GITHUB_REF_NAME_SLUG }}" >> $GITHUB_ENV

      - name: Download and run ghcr containers
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml up -d
        env:
          ROCKY_TAG: ${{ env.GITHUB_REF_NAME_SLUG }}

      - name: Log memory stats
        run: free -h

      - name: Log docker stats
        run: docker stats --no-stream

      - name: Inspect docker network
        if: always()
        run: docker network ls

      - name: Inspect ci network
        if: always()
        run: docker network inspect ci_default

      - name: Seed katalogus boefjes
        run: docker-compose exec -T katalogus python3 -m boefjes.seed

      - name: Seed rocky
        run: docker-compose exec -T rocky python3 manage.py loaddata OOI_database_seed.json

      - name: Create superuser
        run: docker-compose exec -T -e DJANGO_SUPERUSER_PASSWORD=robotpassword rocky python3 manage.py createsuperuser --email robot@localhost --noinput

      - name: Setup dev account
        run: docker-compose exec -T rocky python3 manage.py setup_dev_account

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip

      - name: Install Robot Framework
        run: pip3 install robotframework robotframework-browser robotframework-debuglibrary robotframework-otp robotframework-postgresqldb pyotp

      - name: Initialize rfbrowser
        run: rfbrowser init

      - name: Log memory stats
        run: free -h

      - name: Log docker stats
        run: docker stats --no-stream

      - name: Run Robot Full Onboarding Flow
        run: robot -d tests/robot/results-complete_onboarding -v headless:true tests/robot/complete_onboarding

      - name: Log memory stats
        if: always()
        run: free -h

      - name: Log docker stats
        if: always()
        run: docker stats --no-stream

      - name: Save Docker Compose logs
        if: always()
        run: docker-compose logs > tests/robot/results-docker-compose-logs.txt

      - uses: actions/upload-artifact@v3
        name: Upload Robot Framework reports
        if: always()
        with:
          name: rf-results-complete-onboarding
          path: /home/runner/work/nl-kat-rocky/nl-kat-rocky/nl-kat-rocky/tests/robot/results*
